### ISSUE TITLE
Failed to deploy the panic polkadot UI

### ISSUE THREAD

**Issue by HikaruG** [SimplyVC/panic_polkadot#23]
Hello, 
while trying to build the UI, I encountered the following issue:
```
> panic-polkadot-ui@2.1.3 build /home/ubuntu/panic_polkadot/src/web/ui
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to load config "airbnb" to extend from.
Referenced from: /home/ubuntu/panic_polkadot/src/web/ui/.eslintrc.yml


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! panic-polkadot-ui@2.1.3 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the panic-polkadot-ui@2.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-31T09_54_18_537Z-debug.log
```

Do you have any idea how to solve this error? 
[ui_error.log](https://github.com/SimplyVC/panic_polkadot/files/6235713/ui_error.log)

**Comment by dillu24** [comment]
Hi @HikaruG , thanks for opening up this issue. I will be investing this soon.

**Comment by dillu24** [comment]
@HikaruG - Should be solved in #24 . Will also need to wait for [this](https://github.com/SimplyVC/polkadot_api_server/pull/25) to be merged, as otherwise the alerter won't run as expected.

**Comment by dillu24** [comment]
@HikaruG issue should now be solved.

**Comment by gregorst3** [comment]
Hello, I'm having this issue as well on 2.4.0

> panic-polkadot-ui@2.4.0 build /home/gregorst3/panic_polkadot/src/web/ui
> react-scripts build

Creating an optimized production build...
Failed to compile.

```
Failed to load config "airbnb" to extend from.
Referenced from: /home/gregorst3/panic_polkadot/src/web/ui/.eslintrc.yml


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! panic-polkadot-ui@2.4.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the panic-polkadot-ui@2.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gregorst3/.npm/_logs/2021-11-13T11_18_36_133Z-debug.log
```

```
gregorst3@Substrate-Monitor:~/panic_polkadot/src/web/ui$ cat /home/gregorst3/.npm/_logs/2021-11-13T11_18_36_133Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'build' ]
2 info using npm@6.14.15
3 info using node@v12.22.7
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle panic-polkadot-ui@2.4.0~prebuild: panic-polkadot-ui@2.4.0
6 info lifecycle panic-polkadot-ui@2.4.0~build: panic-polkadot-ui@2.4.0
7 verbose lifecycle panic-polkadot-ui@2.4.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle panic-polkadot-ui@2.4.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/gregorst3/panic_polkadot/src/web/ui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle panic-polkadot-ui@2.4.0~build: CWD: /home/gregorst3/panic_polkadot/src/web/ui
10 silly lifecycle panic-polkadot-ui@2.4.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle panic-polkadot-ui@2.4.0~build: Returned: code: 1  signal: null
12 info lifecycle panic-polkadot-ui@2.4.0~build: Failed to exec build script
13 verbose stack Error: panic-polkadot-ui@2.4.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid panic-polkadot-ui@2.4.0
15 verbose cwd /home/gregorst3/panic_polkadot/src/web/ui
16 verbose Linux 5.4.0-89-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run-script" "build"
18 verbose node v12.22.7
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error panic-polkadot-ui@2.4.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the panic-polkadot-ui@2.4.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Python 3.8.10
node v12.22.7
 npm  v6.14.15
