### ISSUE TITLE
Latest runtime on Kusama seems to have broken the API server. 

### ISSUE THREAD

**Issue by bjweaver** [SimplyVC/panic_polkadot#31]
Seeing this in our logs.

2021-05-15 22:27:16        REGISTRY: Error: Cannot construct unknown type PalletId
    at new DoNotConstruct (/opt/polkadot_api_server/node_modules/@polkadot/types/primitive/DoNotConstruct.js:21:11)
    at new <anonymous> (/opt/polkadot_api_server/node_modules/@polkadot/types/primitive/DoNotConstruct.js:27:9)
    at new Type (/opt/polkadot_api_server/node_modules/@polkadot/types/create/registry.js:340:16)
    at initType (/opt/polkadot_api_server/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/opt/polkadot_api_server/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/opt/polkadot_api_server/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/opt/polkadot_api_server/node_modules/@polkadot/types/create/registry.js:297:39)
    at /opt/polkadot_api_server/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
    at Array.reduce (<anonymous>)
    at /opt/polkadot_api_server/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
2021-05-15 22:27:16        API/INIT: Error: FATAL: Unable to initialize the API: createType(PalletId):: Cannot construct unknown type PalletId

**Comment by dillu24** [comment]
Hi @bjweaver , what veraion of the Polkadot API server are you running? And are you running the latest version for the nodes?

**Comment by bjweaver** [comment]
Aaah, looks like I need to update..   It looks like the prebuild on dockerhub might be broken?
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:

**Comment by bjweaver** [comment]
ok, I have it working again.   I had to build the 1.28.1 myself, something isn't right with the one hosted on dockerhub. Now things are working. thanks!
